service: aws-python-flask-api

frameworkVersion: '2 || 3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.10

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements


#service: aws-python # NOTE: update this with your service name
#
#frameworkVersion: '2 || 3'
#
#
#provider:
#  name: aws
#  runtime: python3.8
#  lambdaHashingVersion: 20201221
#
#functions:
#  hello:
#    handler: handler.hello
#plugins:
#  - serverless-python-requirements
